package com.tinhvan.hd.utils;

import java.util.List;

public class ConstantStatus {

    public static final String SIGNED_CONTRACT = "DOCUMENT ENTRY,DOCUMENT VERIFICATION,DISBURSEMENT WRAPPER,INI,REQUEST FOR DISBURSEMENT,EXCEPTION APPROVAL DUMMY,DISBURSEMENT AUTHORIZE,TRANSFER CONFIRMATION AND AUTHORIZE,GENERATE AGREEMENT NO. (CHECK)GENERATE AGREEMENT NO. (CHECK),FINAL DISBUSERMENT CHECK";

    public static final String WAIT_FOR_SIGNING_CONTRACT = "CONTRACT PRINTING,PASS ACCOUNT ENTRY,DOCUMENT GENERATION";

    public static final String CURRENT_CONTRACT = "LIVE,CONTENSIOUS,LEGAL TERMINATION,LEGAL TERMINATED";

    public static final String CONTRACT_DISBURSED = "MATURED,EARLY TERMINATION,LEGAL TERMINATED";

//    public static final String WAIT_FOR_APPROVAL_CONTRACT = "APPROVAL";

}
