
server:
  port: 8807

spring:
  datasource:
    url: jdbc:postgresql://192.168.75.205:5432/hd_dev
    username: tvo
    password: hd@123
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
  application:
    name: authorize-service
  #rabbitmq config
  rabbitmq:
    host: 192.168.75.205
    port: 5672
    username: tvo
    password: hd@123

  hikari:
    connection-timeout: 60000
    maximum-pool-size: 5
  # ===============================
  # FILE
  # ===============================
  ## MULTIPART (MultipartProperties)
  # Enable multipart uploads

  servlet:
    multipart:
      enabled: true
      # Threshold after which files are written to disk.
      file-size-threshold: 2KB
      # Max file size.
      max-file-size: 200MB
      # Max Request Size
      max-request-size: 215MB

  ## File Storage Properties
  # All files uploaded through the REST API will be stored in this directory
file:
  upload-dir: ./uploads



#logging:
#  level:
#    com.netflix.eureka: OFF
#    com.netflix.discovery: OFF
#
#eureka:
#  instance:
#    appname: authorize-service
#  client:
#    enabled: true
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://192.168.75.205:8761/eureka/
#invoke
app:
  module:
    filehandler:
      service:
        url: http://192.168.75.205:8802/api/v1/filehandler
    staff:
      service:
        url: http://192.168.75.205:8808/api/v1/staff
    contract:
      service:
        url: http://192.168.75.205:8806/api/v1/contract




